version: '3.9'

services:
  mongodb_db:
    restart: always
    image: mongo:latest
    volumes:
      - ./docker_data/db:/data/db
      - ./mongo:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
    command: mongod
    env_file:
      - .env
    environment:
      MONGO_DATA_DIR: /docker_data/db
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}

  bot:
    build: .
    working_dir: /application
    volumes:
      - .:/application
#    environment:
#      - BOT_API_TOKEN=$API_TOKEN
    depends_on:
      - mongodb_db
    links:
      - mongodb_db
    command: python main.py
